import { Document, Page, Text, View, StyleSheet, Font } from "@react-pdf/renderer";
import { CategoryData, TrendData } from "@/app/actions/analytics";

// Register Font
// Font.register({
//     family: "Inter",
//     src: "https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hjp-Ek-_EeA.ttf",
// });

const styles = StyleSheet.create({
    page: { padding: 40, color: "#1e293b" },
    header: { marginBottom: 30, textAlign: "center" },
    title: { fontSize: 24, fontWeight: "bold", marginBottom: 6 },
    subtitle: { fontSize: 12, color: "#64748b" },
    section: { marginBottom: 20 },
    sectionTitle: { fontSize: 14, fontWeight: "bold", marginBottom: 10, textTransform: "uppercase", color: "#3b82f6" },
    row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 6 },
    text: { fontSize: 10 },
    bold: { fontWeight: "bold" },
    chartPlaceholder: { marginTop: 10, height: 100, backgroundColor: "#f1f5f9", justifyContent: "center", alignItems: "center" },
});

interface MonthlyReportPDFProps {
    metrics: {
        tasksAssigned: number;
        completionRate: number;
        timeConsumed: number;
        topCategory: string;
    };
    breakdown: CategoryData[];
    insights: string[];
}

export function MonthlyReportPDF({ metrics, breakdown, insights }: MonthlyReportPDFProps) {
    return (
        <Document>
            <Page size="A4" style={styles.page}>
                {/* Header */}
                <View style={styles.header}>
                    <Text style={styles.title}>Calma Monthly Report</Text>
                    <Text style={styles.subtitle}>
                        Focus analysis for {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}
                    </Text>
                </View>

                {/* Executive Summary */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>Executive Summary</Text>
                    <Text style={{ fontSize: 12, marginBottom: 16, lineHeight: 1.5 }}>
                        This month, you completed {metrics.completionRate}% of your assigned tasks, totaling {metrics.timeConsumed} hours of focus time.
                        Your primary area of attention was {metrics.topCategory}.
                    </Text>

                    {insights.map((insight, i) => (
                        <Text key={i} style={{ fontSize: 10, marginBottom: 4, color: "#475569" }}>• {insight}</Text>
                    ))}
                </View>

                {/* Breakdown Table (Simulated) */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>Category Breakdown</Text>
                    {breakdown.map((cat, i) => (
                        <View key={i} style={[styles.row, { borderBottom: "1px solid #e2e8f0", paddingBottom: 4 }]}>
                            <Text style={styles.text}>{cat.name}</Text>
                            <Text style={styles.text}>{cat.value} mins</Text>
                        </View>
                    ))}
                </View>

                {/* Footer */}
                <View style={{ position: "absolute", bottom: 30, left: 40, right: 40, textAlign: "center" }}>
                    <Text style={{ fontSize: 8, color: "#94a3b8" }}>
                        Generated by Calma Protocol
                    </Text>
                </View>
            </Page>
        </Document>
    );
}
