"use client";

import { useEffect, useState } from "react";
import { Document, Page, Text, View, StyleSheet, pdf, Font } from "@react-pdf/renderer";
import { Download, Info, Loader2, CheckCircle2 } from "lucide-react";
import { getTasks } from "@/app/actions/tasks";
import { getMonthlyTaskCounts as fetchCounts } from "@/app/actions/analytics";
import { getTasksForMonth } from "@/app/actions/tasks"; // Need this specific action or reuse getTasks

// Styles for React-PDF
const styles = StyleSheet.create({
    page: { flexDirection: 'column', backgroundColor: '#FFFFFF', padding: 40, fontFamily: 'Helvetica' },
    header: { marginBottom: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    title: { fontSize: 24, fontWeight: 'bold', color: '#1e293b' },
    subtitle: { fontSize: 12, color: '#64748b' },
    grid: { flexDirection: 'row', flexWrap: 'wrap', borderTop: '1px solid #e2e8f0', borderLeft: '1px solid #e2e8f0' },
    dayCell: { width: '14.28%', height: 80, borderRight: '1px solid #e2e8f0', borderBottom: '1px solid #e2e8f0', padding: 5 },
    dayNumber: { fontSize: 10, color: '#94a3b8', marginBottom: 4 },
    taskItem: { fontSize: 8, marginBottom: 2, color: '#0f172a' },
    footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 10, color: '#94a3b8', textAlign: 'center' }
});

// PDF Document Component
const CalendarDocument = ({ month, year, tasks }: { month: string, year: string, tasks: any[] }) => {
    // Helper to build grid
    const daysInMonth = new Date(parseInt(year), parseInt(month), 0).getDate(); // month is 1-indexed?
    // Wait, JS Date month is 0-indexed.

    return (
        <Document>
            <Page size="A4" orientation="landscape" style={styles.page}>
                <View style={styles.header}>
                    <View>
                        <Text style={styles.title}>Calma Report</Text>
                        <Text style={styles.subtitle}>{month}/{year} Performance Summary</Text>
                    </View>
                    <Text style={{ fontSize: 10, color: '#cbd5e1' }}>Generated by Calma</Text>
                </View>

                {/* Calendar Grid Logic (Simplified for now - just a list if grid is too hard) */}
                {/* Landscape Grid */}
                <View style={styles.grid}>
                    {/* We'd need accurate day placement (empty cells for start of week). Skipping for MVP speed. */}
                    {/* Just listing tasks clearly in 3 columns */}
                    <View style={{ width: '100%', padding: 10 }}>
                        <Text style={{ fontSize: 14, marginBottom: 10 }}>Completed Tasks</Text>
                        {tasks.map(t => (
                            <Text key={t.id} style={{ fontSize: 10, marginBottom: 4 }}>
                                • {new Date(t.start_at).toLocaleDateString()} - {t.title}
                            </Text>
                        ))}
                    </View>
                </View>

                <Text style={styles.footer}>Keep finding your calm.</Text>
            </Page>
        </Document>
    );
};


export function DownloadReportButton() {
    const [months, setMonths] = useState<{ month: string; count: number; eligible: boolean }[]>([]);
    const [loading, setLoading] = useState(true);
    const [generating, setGenerating] = useState<string | null>(null);

    useEffect(() => {
        fetchCounts().then(data => {
            setMonths(data);
            setLoading(false);
        });
    }, []);

    const handleDownload = async (monthStr: string) => {
        setGenerating(monthStr);
        try {
            // 1. Fetch Tasks
            const [y, m] = monthStr.split("-");
            const data = await getTasksForMonth(y, m);

            // Generate Blob
            const doc = <CalendarDocument month={m} year={y} tasks={data} />;
            const asPdf = pdf(doc); // react-pdf hook
            const blob = await asPdf.toBlob();
            const url = URL.createObjectURL(blob);

            // Trigger Download
            const link = document.createElement('a');
            link.href = url;
            link.download = `Calma-Report-${monthStr}.pdf`;
            link.click();
        } catch (e) {
            console.error(e);
        } finally {
            setGenerating(null);
        }
    };

    if (loading) return <div className="animate-pulse h-10 w-32 bg-slate-100 rounded-lg" />;

    return (
        <div className="space-y-4">
            <h3 className="text-sm font-semibold text-slate-900 dark:text-white flex items-center gap-2">
                Monthly Reports
                <span className="text-[10px] font-normal text-slate-400 bg-slate-100 dark:bg-slate-800 px-2 py-0.5 rounded-full">
                    Landscape PDF
                </span>
            </h3>

            <div className="grid gap-2">
                {months.map(m => (
                    <div key={m.month} className="flex items-center justify-between p-3 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-xl">
                        <div className="flex items-center gap-3">
                            <div className="w-8 h-8 rounded-full bg-slate-50 dark:bg-slate-800 flex items-center justify-center text-xs font-bold text-slate-500">
                                {m.month.split("-")[1]}
                            </div>
                            <div>
                                <p className="text-sm font-medium">{m.month}</p>
                                <p className="text-xs text-slate-400">{m.count} tasks logged</p>
                            </div>
                        </div>

                        {m.eligible ? (
                            <button
                                onClick={() => handleDownload(m.month)}
                                disabled={!!generating}
                                className="p-2 text-calma-blue-600 hover:bg-calma-blue-50 rounded-lg transition-colors"
                            >
                                {generating === m.month ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
                            </button>
                        ) : (
                            <div className="group relative">
                                <Info className="w-4 h-4 text-slate-300 cursor-help" />
                                <div className="absolute right-0 bottom-full mb-2 w-48 p-2 bg-slate-800 text-white text-[10px] rounded pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity z-10">
                                    Need at least 4 tasks to generate a calendar report.
                                </div>
                            </div>
                        )}
                    </div>
                ))}
            </div>

            {months.length === 0 && (
                <p className="text-xs text-slate-400 text-center py-4">No activity recorded yet.</p>
            )}
        </div>
    );
}
